git_repo: ""
git_branch: main
git_remote: origin
story_dir: /var/folders/zy/rtw59dpj6x95f3g4xzx5j08c0000gp/T/TestListStories3328577842/001/stories
pair_file: pair.json
author_name: ""
author_email: ""
pair_name: ""
jira_host: ""
jira_token: ""
jira_project: ""
jira_user: ""
