git_repo: test-project
git_branch: main
git_remote: origin
story_dir: ""
pair_file: ""
author_name: john.doe
author_email: ""
pair_name: ""
jira_host: ""
jira_token: ""
jira_project: ""
jira_user: ""
