git_repo: test-project
git_branch: main
git_remote: origin
story_dir: stories
pair_file: pair.json
author_name: test-user
author_email: ""
pair_name: ""
jira_host: ""
jira_token: ""
jira_project: ""
jira_user: ""
